// src/components/search/PostList.tsx
import PostCard from '@/components/search/PostCard';
import { Posts } from '@/types/post';

interface PostListProps {
  posts: Posts;
}

const PostList = ({ posts }: PostListProps) => {
  return (
    <div className="flex flex-1 flex-col">
      <ol className="relative mx-0 my-[20px] flex w-full  flex-col gap-[40px] p-0">
        {posts.posts.map((post) => (
          <PostCard
            key={post.slug}
            title={post.data.title}
            titleImage={post.data.titleImage}
            description={post.data.description}
            date={post.data.date}
            path={post.slug}
          />
        ))}
      </ol>
    </div>
  );
};

export default PostList;

// src/lib/components/Posts/PostList.svelte
<script>
	import PostCard from '$lib/components/Posts/PostCard.svelte';

	export let posts;
</script>

<ol class="wrapper">
	{#each posts.posts as post}
		<PostCard
			path={post.slug}
			title={post.title}
			description={post.description}
			titleImage={post.titleImage}
			date={post.date}
		/>
	{/each}
</ol>
