// src/components/PostList.tsx
import React from 'react';
import { Posts } from '@/app/page';
import PostCard from '@/components/PostCard';

interface PostListProps {
  posts: Posts[];
}

const PostList = ({ posts }: PostListProps) => {
  return (
    <ol className="relative mx-0 my-[20px] flex w-full flex-col gap-[40px] p-0">
      {posts.map((post) => (
        <PostCard
          key={post.slug}
          title={post.data.title}
          titleImage={post.data.titleImage}
          category={post.data.category}
          description={post.data.description}
          date={post.data.date}
          path={post.slug}
        />
      ))}
    </ol>
  );
};

export default PostList;

// src/lib/components/Posts/PostList.svelte
<script>
	import PostCard from '$lib/components/Posts/PostCard.svelte';

	export let posts;
</script>

<ol class="wrapper">
	{#each posts.posts as post}
		<PostCard
			path={post.slug}
			title={post.title}
			description={post.description}
			category={post.category}
			titleImage={post.titleImage}
			date={post.date}
		/>
	{/each}
</ol>
